[project]
name = "scripts-csvtoicalendar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "icalendar>=6.3.1",
    "pytz>=2025.2",
]
[tool.pyright]
venvPath = "."
venv = ".venv"
